[project]
name = "readwise-to-podcast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notebooklm-py>=0.3.2",
    "playwright>=1.58.0",
]
